appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: ANfs8YdiOdxo3WILSSAGCdqWM898eo86kUD44jDoT1AWpUETlSbfIxPmfHXmbAFPPCZGbGpY+RRoA0AZSMlkIeRCfWfEjhAnpB4Fla7hi566BNZlvzjHcQEGUI3ccaGA3ibeneJI1DtYasvkAWIWjTsr4Red5g1R8qztMW0ZUYHmfWgqY/HAqCJbvlq+j/dGHKlOP3RnHUt0AGgmRXKP9rN4uJchvwnHbI7ZirS4gidlzijwJ7fIrINMnj05qZPEFfEVr8mPg8yXeGnyRwtsCGQkj6T0N1JLDNSkAnEDw/RaS4XUZnJDiehs6vmieJ2PyhFj3FJO2+sA+1U5j8sNubMOtm60DNyVToTVAI0eMU9yZfCKqY+UsyFF82t8gvAWY1NsH6ow+j+97lZOtV7B07kzpGcR0yEBGpFaH8noYmYA9vwIPlR+eFO/w+y0xjOeHx8aDAukJatuQx/Kobg28jTFlLs2QPVtByu7ojOKtLgl63s53/8jx+DuLAtVwbeQr46be3EGfhP0syeDk57WG0/kGXX9N30usmteqeTr4P8qHIWARFpFi8/pOvcc5G+gKB9SB3cSxQcGTd/YcW5mJpB8/5anCmsIw3s0NREKW4h65GkQv2iN4OebUJk2k55NwufHbs1OmIt8FVygmpIY/DVgl7vtLrPf777a0Zthbbo=}
bot:
  automerge: true
